### PR TITLE
Set up test coverage using coveralls

### PR DESCRIPTION
**Pull request by Huulamnguyen**
**What does this PR do?**
- This PR sets up test coverage by Coveralls

**Description of Task to be completed?**
- Setting up test coverage by Coveralls

**How should this be manually tested?**

### CODE REVIEW

**Comment by alexkayabula** [comment]
@Huulamnguyen please add the corresponding test coverage badge to the readme.

**Comment by alexkayabula** [comment]
@Huulamnguyen change the title of the PR to `Set up test coverage using coveralls`.

**Comment by Huulamnguyen** [comment]
> @Huulamnguyen change the title of the PR to `Set up test coverage using coveralls`.

Yes. I changed the title

**Comment by Huulamnguyen** [comment]
> @Huulamnguyen please add the corresponding test coverage badge to the readme.

I added the corresponding test coverage badge to the readme. Please review and let me know if there is any improvement I should work on?

Thanks,

**Pull request merged**
