### PR TITLE
Set up project structure

### PR DESCRIPTION
**Pull request by Huulamnguyen**
**What does this PR do?**
This PR sets up the project structure.

**Description of Task to be completed**
Set up the project structure.

**How should this be manually tested?**
NAN

### CODE REVIEW

**Comment by alexkayabula** [comment]
@Huulamnguyen please add all required files and folders.

**Comment by Huulamnguyen** [comment]
> @Huulamnguyen please add all required files and folders.
Yes. I'm going to do that. ^^

**Comment by Huulamnguyen** [comment]
@alexkayabula I finished setting up the project structure. Please let me know if there is anything should I improve and add. Many thanks.

**Comment by alexkayabula** [comment]
@Huulamnguyen Add tests folder and test files. Also add a config.py file.

**Comment by Huulamnguyen** [comment]
> @Huulamnguyen Add tests folder and test files. Also, add a config.py file.
Done. Please review and let me know if there is anything else should I improve

**Review by alexkayabula — APPROVED** [review]
LGTM.Thank you.

**Comment by Huulamnguyen** [comment]
> LGTM.Thank you.

Thank you, Alex

**Pull request merged**
